import { createApp } from "vue";
import router from "./router/index.js";
import App from "./App.vue";
import "bootstrap/dist/css/bootstrap.min.css";
import "@fortawesome/fontawesome-free/css/all.css";
import ElementPlus from "element-plus";
import "element-plus/dist/index.css";
import VueAnimXyz from "@animxyz/vue3";
import "@animxyz/core";
import AOS from "aos";
import "aos/dist/aos.css";
const app = createApp(App);
app.use(AOS.init());
app.use(router);
app.use(VueAnimXyz);
app.use(ElementPlus);
app.mount("#app");
